### ISSUE TITLE
New Example: mask

### ISSUE THREAD

**Issue by ghost** [formly-js/angular-formly-website#10]
I would like an example that demonstrates: using masks input, ng-mask.
thanks.

**Comment by kentcdodds** [comment]
Sorry, I didn't realize I wasn't watching the repo and just saw this for the first time now. Do you still need this example? If so, I'll try to get this example in as soon as possible. Thanks for your patience! Please let me know.

**Comment by ghost** [comment]
Hi Kent, thank you for your reply & thank you for this great library!!!
I'm developing a very big project with hundrads of schemas with complicated masks, for example: geo masks.
I want to know the best way to approch this.

If you dont mind, I would like to ask you a question: 
I want to embed angular-translate into formly, what is your recommendation for this?

Thanks a lot for you kind help.

**Comment by kentcdodds** [comment]
I created an example request for the translation question you asked (#13). I'll let you know when these are added.

**Comment by kentcdodds** [comment]
Here's the example! http://angular-formly.com/#/example/very-advanced/ng-mask

**Comment by ghost** [comment]
Thank's \* 10^6.

**Comment by hrishi1183** [comment]
ng-mask is not working conditional.. 
expressionProperties: {
            "templateOptions.mask": "true ? '9999999999-99' : '(999)999-999'"
          },
ex: one text field need to have different format based on its previous selection.. but expressionProperties is not working with ng-mask

http://jsbin.com/wixawijuca/1/edit?js,output

can anybody has any idea how to make ng-mask conditional
