### ISSUE TITLE
New Example: unit-tests angular formly

### ISSUE THREAD

**Issue by tlimpanont** [formly-js/angular-formly-website#11]
I would like an example that demonstrates:

unit-tests examples

**Comment by kentcdodds** [comment]
Thanks! This is definitely needed! I'll see what I can do to develop an example of this soon.

**Comment by kentcdodds** [comment]
I'm definitely planning on creating an example for this one. Sorry it's taken so long. Until I can get to it. The `angular-formly` tests are pretty good. I recommend you look at them. [Here's one](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.test.js#L79-L89) that tests the presense of the `formControl` on the field's scope. You could test for other things in like manner.

**Comment by tlimpanont** [comment]
Thankzzz it's OK we all have tight schedules in our own life. But I
appreciate  your effort very much. The examples are great!

**Comment by kentcdodds** [comment]
I've started work on it here: http://jsbin.com/hayixo/edit

Haven't actually tested anything yet... A bit of setup to do.

**Comment by kentcdodds** [comment]
Here's an example for you :-) http://angular-formly.com/#/example/other/testing

**Comment by tlimpanont** [comment]
You nailed it!! Thnkzzz

2015-06-08 18:32 GMT+02:00 Kent C. Dodds notifications@github.com:

**Comment by tlimpanont** [comment]
By the way, do you have nesting formly-forms examples?

2015-06-09 8:31 GMT+02:00 Theuy Limpanont theuy.limpanont@gmail.com:
