### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by gussoler** [formly-js/angular-formly-website#17]
I would like an example that demonstrates a responsive form using formly:

Using a json model I created a layout that looks like this:

<table>
<tr><td><b>Your Information</b></td><td><b>Event</b></td><td><b>Venue</b></td></tr>
<tr><td>Full name</td><td>name</td><td>City</td></tr>
<tr><td>Company</td><td>date</td><td>Country</td></tr>
</table>

It works fine for large/medium screens, but in a smaller screen it is shown as:

<table>
<tr><td><b>Your Information</b></td><tr>
<tr><td><b>Event</b></td><tr>
<tr><td><b>Venue</b></td><tr>
<tr><td>Full name</td><tr>
<tr><td>name</td><tr>
<tr><td>City</td><tr>
<tr><td>Company</td><tr>
<tr><td>date</td><tr>
<tr><td>Country</td><tr>
</table>

But, I would like to achieve this:

<table>
<tr><td><b>Your Information</b></td><tr>
<tr><td>Full name</td><tr>
<tr><td>Company</td><tr>
<tr><td><b>Event</b></td><tr>
<tr><td>name</td><tr>
<tr><td>City</td><tr>
<tr><td><b>Venue</b></td><tr>
<tr><td>City</td><tr>
<tr><td>Country</td><tr>
</table>

I tried using fieldgroups, wrappers and templateManipulators in combination with bootstrap, but I can't achieve the latest behaviour.

Thanks in advance for any help!

**Comment by kentcdodds** [comment]
If you could show me how you would accomplish this using regular html, that could help me know how to accomplish it using formly.

**Comment by gussoler** [comment]
I think I was wrong, instead of creating a single form, I decided to create three different forms using the same model. With this approach, every time the screen is reduced each field stays grouped with their form, avoiding the "issue" that I reported.

**Comment by kentcdodds** [comment]
Terrific solution. :+1:
