### ISSUE TITLE
Add user to angular-formly site: Mongolar

### ISSUE THREAD

**Issue by jasonrichardsmith** [formly-js/angular-formly-website#19]
# Add mongolar to users

Project/Company Name: mongolar

Link: https://github.com/mongolar/mongolar

Logo:

![logo for mongolar]()

Short Description:

Mongolar uses angular-formly for all its form generations

---

**Comment by kentcdodds** [comment]
Looks like the logo is missing.

**Comment by jasonrichardsmith** [comment]
no logo yet, it said optional

**Comment by kentcdodds** [comment]
Ah, I was confused by:

> ![logo for mongolar]()

Thanks!
