### ISSUE TITLE
New Example: File Input in form

### ISSUE THREAD

**Issue by SagiMedina** [formly-js/angular-formly-website#2]
Hi, I would like to see an example of a file input type please.

**Comment by cve** [comment]
+1

**Comment by kentcdodds** [comment]
Sorry, I didn't realize I wasn't watching the repo and just saw this for the first time now. Do you still need this example? If so, I'll try to get this example in as soon as possible. Thanks for your patience! Please let me know.

**Comment by SagiMedina** [comment]
@kentcdodds I have already did something with lumx template, you can have a look there. if you want I can do the same for others templates too.

**Comment by kentcdodds** [comment]
@SagiMedina, that would be awesome to get an example for the angular-formly website :-)

**Comment by stevebluck** [comment]
It would be really cool to get an example of a file upload template. I'm using https://github.com/nervgh/angular-file-upload and can't seem to get the two talking to each other.

**Comment by kentcdodds** [comment]
I'd love to make an example for this one, but I just haven't been able to find time. Here's the one I use at work. I hope that you can find it useful:

https://gist.github.com/kentcdodds/8bfdbf832b3cebfb050f

**Comment by nextglory** [comment]
I just posted an file upload example:
http://jsbin.com/vuweca/15/edit?html,css,js,output
It's never validate ok regardless of selecting a file, any suggestions? @kentcdodds

Beer!!!

**Comment by kentcdodds** [comment]
@nextglory, so the problem is that angular isn't updating the model when you select a file. I'm not sure how angular treats inputs with the `file` type, but this isn't an angular-formly thing. That field's ng-model technically is empty. I think this is why directives have popped up to solve this problem. I recommend you look around for one.

**Comment by nextglory** [comment]
@kentcdodds Thanks and I will check the directive solution, please leave a tip when you got a better solution, thanks...........

**Comment by Luddinus** [comment]
+1

**Comment by ejbaker** [comment]
+1

For looking at and learning from "what you use at work", it would really help to have any idea what "azBase" is, because your example extends that... without knowing what it is, or -- ideally -- whether any part of it is critical (rather than just, say, tying in the error message output to something else), it's a bit daunting.

**Comment by kentcdodds** [comment]
Sorry, I no longer work there so I don't have access to that code :-(

**Comment by sukrosono** [comment]
[Here](http://jsbin.com/koredu/edit?html,output) we go, and i will make new PR for this one :smile: .

**Comment by ejbaker** [comment]
@brutalcrozt Wow, great work!! I was most of the way there with ng-file-upload... but this is attractively simple. Does it work to send the file? Like, say, if you had mutler + NodeJS set up on the backend to receive and interpret file types...

**Comment by Luddinus** [comment]
How do I send the file to Laravel? It sends a "plain object"

**Comment by sukrosono** [comment]
@Luddinus you may take a look [here](https://www.codetutorial.io/laravel-5-file-upload-storage-download/) , if i am not wrong it utilize the name attribute on input element, so backend match it's name

**Comment by CJYate** [comment]
@brutalcrozt  thanks for the JSbin link. Another step forwards for me; I still need to make it upload the file, but this should be a good start.

**Comment by CJBrew** [comment]
Why is setting up a file upload from formly **so** difficult?! :-1:  :-1: :-1: :-1: :-1:
@brutalcrozt the UI is fine; where is the actual file import supposed to happen?

**Comment by CJYate** [comment]
FYI I have decided to abandon trying to get Formly to host a file upload control. It's a nightmare -- although I can see @brutalcrozt 's code will let me do the upload in my controller... I'll just host the upload thing outside of Formly; obviously a simpler solution!

**Comment by ginniarora** [comment]
@brutalcrozt , your code - http://jsbin.com/koredu/edit?js,output gives only name of the file. I need path or file data also, so that i can save the file at some remote location and read it back from there.
Please advice

**Comment by sukrosono** [comment]
@ginniarora AFAIK you can't get the file path on client side, for security reason, you might want read related [SO question](https://stackoverflow.com/a/15201258/2368696). For the file data you already have it via your backend.

**Comment by avashgtm** [comment]
I created this solution for one of my project http://jsbin.com/yotavivuge/edit?html,js,output
