### ISSUE TITLE
File-Input

### ISSUE THREAD

**Issue by algone** [formly-js/angular-formly-website#27]
I would like an example that demonstrates:File input using bootstrap template. I already see that there is a file-input example lumx template. Could we have also an example that uses bootstrap template? 

The reason is that, I would like to use both the file input and a wizzard, The bootstrap template has a wizzard but not file input, on the other hand lumx template has file input but not a wizzard.

**Comment by kentcdodds** [comment]
Hi @algone, this has been requested already. I'll try to get to it soon. Closing this in favor of #2.
