### ISSUE TITLE
Show/Hide group of fields

### ISSUE THREAD

**Issue by sistemanick** [formly-js/angular-formly-website#29]
I would like an example that demonstrates: showing and hiding a whole group of fields based on model values

e.g.
{ key: 'showGroup', type: 'checkbox', templateOptions: { label: 'Show group' } },  
{
      fieldGroup: [
            { key: 'field1', type: 'input', templateOptions: { required: true, label: 'Field 1' } },
            { key: 'field2', type: 'input', templateOptions: { required: true, label: 'Field 2' } }  
      ],
      expressionProperties: {
            hide: '!model.showGroup'
      }  
}

**Comment by kentcdodds** [comment]
Instead of expressionProperties, use hideExpression.
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by sistemanick** [comment]
Cool that works. Thanks!
