### ISSUE TITLE
New Example: Tabs.

### ISSUE THREAD

**Issue by levalencia** [formly-js/angular-formly-website#40]
Can you please develop an example using tabs?

**Comment by kentcdodds** [comment]
Done :+1: http://angular-formly.com/#/example/integrations/ui-bootstrap-tabs

**Comment by kannajune** [comment]
Hi, Can you please explain, how to get active tab ..?

**Comment by kentcdodds** [comment]
Documentation for tabs can be found here: https://angular-ui.github.io/bootstrap/#/tabs

**Comment by kannajune** [comment]
thank you
