### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by pdarscht** [formly-js/angular-formly-website#42]
I would like an example that demonstrates: how to detect a change in any of the form fields (i.e. trigger an event "data has changed" when something changes value within the form).

**Comment by kentcdodds** [comment]
You could very easily do your own `$watch` on the model in your controller. This example is not at all angular-formly specific, so I wont make a full example. But here's the idea:

``` javascript
$scope.model = {
  firstName: 'Joe',
  lastName: 'Ford'
};

// your own $watch here.
$scope.$watch('model', function(newValue, oldValue) {
  console.log(newValue, oldValue);
}, true);
```
