### ISSUE TITLE
Typing inside a text input is extremely slow on iPad

### ISSUE THREAD

**Issue by satyendera** [formly-js/angular-formly-website#46]
i am using angular formly for dynamic form rendering. 
it's working fine on desktop but in ipad textbox/textarea typing is very slow even i make autocomplete off , no watchers..

**Comment by satyendera** [comment]
formlyConfigProvider.setWrapper({
            name: 'HorizontalInputtextarea',
            template: [
              '<div style="float: left;" class="HorizontalInputtextarea">',
                  '<label for="{{::id}}" style="width: 13.25em;" ng-class="{\'notes\': \'{{to.Notes}}\' == \'true\' }" class="text-left col-md-6 control-label padding-40"  >',
                    '{{to.label}}',
                  '</label>',
                  
                  '<div class="col-md-6 padding-40" style="width: 42em;" >',
                  '<formly-transclude></formly-transclude>',
                '</div>',
              '</div>'
            ].join(' ')
          });

**Comment by kentcdodds** [comment]
@satyendera, this is not the repository to file bug reports or feature requests for angular-formly. To file an issue on the real project, please see: [issue.angular-formly.com](http://issue.angular-formly.com)
