### ISSUE TITLE
New Example:update egghead IO lessons.,

### ISSUE THREAD

**Issue by sathishjayapal** [formly-js/angular-formly-website#47]
Just a suggestion when I pull the latest release from github, it is bit different than the egghead IO for example the "angular-formly" is now changed to "formly" and the same goes for bootstrap.. One more request, can you do an example integrating a Rails application?? Thanks.

**Comment by kentcdodds** [comment]
Actually, the `angular-formly` and `angular-formly-templates-bootstrap` libraries are the same as they've always been with regards to filenames. Could you check again?

The one thing that has changed is `api-check` (changed from `apiCheck.js` to `api-check.js`). This was a breaking change and was [well documented](https://github.com/kentcdodds/api-check/blob/master/CHANGELOG.md#700-beta0). I don't think that I'll get to updating those lessons. That's not normally a big hurdle for people and most would benefit more from new lessons on other concepts than me fixing the old lesson on something like that.

As for integration with a Rails application, I've never done rails before, but I'd direct you to one of these sources of help:
- http://question.angular-formly.com
- http://mailing-list.angular-formly.com
- http://chat.angular-formly.com

Thanks for your interest in angular-formly!
