### ISSUE TITLE
New Example: Field Group

### ISSUE THREAD

**Issue by jonathandick** [formly-js/angular-formly-website#49]
First off, this thing is awesome. 

I'm an HIV doc working in Kenya but also lead a team building data collection tools for our rural sites. We have an established system (OpenMRS) which allows for us to submit "encounters" of "obs". An obs is a key value pair, such as key="is the patient on hiv treatment?" value=Yes/No. 

An important feature for us is to be able to group sets of questions together which are linked. So there might be a concept like a medication order which consists of a drug, dose, quantity and duration. When stored in the database, these would be linked together via a common uuid. 

I can see clearly how we would use angular-formly to represent ungrouped elements. But, I'm not sure how to organize it to allow for grouped items. Note, that not only do i need to collect data this way. But, later, we may need to edit it. So I need to be able to take a group and populate the formly element representing the group.

Any tips would be very much appreciated. 

Thanks,

Jonathan Dick

**Comment by kentcdodds** [comment]
Hi Jonathan! We have an example that demonstrates `fieldGroup` here: http://angular-formly.com/#/example/bootstrap-specific/advanced-layout

I hope that's sufficient. I don't think that your use case is general enough to warrant an example all on its own, but you could definitely ask a specific question using [help.angular-formly.com](http://help.angular-formly.com)

**Comment by jonathandick** [comment]
Thanks for the fast reply. Will take a look at the example and follow-up if
necessary.

**Comment by jonathandick** [comment]
Kent, I decided to utilize a custom function to set the model for each
field. This lets me customize the binding to match a different schema then
simply binding to model.field. Take a look at
https://github.com/jonathandick/angular-formly
if it interests you.

Now, for a type like a checkbox, I'd like to save a value associated with
the element rather than the value true. I tried to set up a watcher on the
checkbox so that I could change the model appropriately. However, the
watcher only seems to be watching the base model. Anyway to get the watcher
to trigger in this scenario?

Jonathan

**Comment by kentcdodds** [comment]
I'm on vacation right now, but I would recommend creating a custom type
that utilizes ng-true-value and ng-false-value

Or you can make a pull request to the bootstrap templates to support this.

Or you can use ngModelAttrs and extend the existing type. It's a little
complicated, but it's quite effective.
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by jonathandick** [comment]
Thanks again for your fast response. Enjoy your vacation!
