### ISSUE TITLE
New Example: grid-based form with right aligned labels

### ISSUE THREAD

**Issue by ronaldborman** [formly-js/angular-formly-website#5]
I would like an example that demonstrates:
a form layed out using a css grid system with labels that are placed left of the input and are right aligned. This was discussed earlier in angular-formly issue 267.

**Comment by kentcdodds** [comment]
Sorry, I didn't realize I wasn't watching the repo and just saw this for the first time now. Do you still need this example? If so, I'll try to get this example in as soon as possible. Thanks for your patience! Please let me know.

**Comment by ronaldborman** [comment]
No problem, I've put together a basic layout myself. But I like to learn from a pro so I still could use a 'battle tested' example. No pressure though!

**Comment by kentcdodds** [comment]
Hey @rborman, I forgot, there's already an example like this! http://angular-formly.com/#/example/other/bootstrap-horizontal

Please re-open if this is not sufficient.
