### ISSUE TITLE
Validating json loaded data

### ISSUE THREAD

**Issue by aguirrel** [formly-js/angular-formly-website#57]
Hi guys,

I'm checking "json powered" example to load data.

http://jsbin.com/pakivu/7/edit?html,css,js,output

I want formly to validate data when is loaded.  I added "ipAddress":"abc" to json in response:

http://jsbin.com/mifujasexi/edit?html,css,js,output

It doesn't work out of the box, but if I add: "validation": {"show":true} to field definition works as expected:

``` javascript
       {
            "key": "ipAddress",
            "type": "ipAddress",
            "templateOptions": {
              "label": "IP Address"
            },
            "validation": {"show":true}
          },
```

Is there some way to **not** add "validation": {"show":true} to all fields? Some general configuration way?

Thanks a lot!

**Comment by kentcdodds** [comment]
I would do this: https://jsbin.com/hofizi/edit?html,js,output

**Comment by kentcdodds** [comment]
Hopefully that helps. I'm going to go ahead and close this issue though because the issues are reserved for feature requests and bug reports. If you need help, follow the instructions here: http://help.angular-formly.com Thanks!

**Comment by aguirrel** [comment]
Hi Kent!

Thanks a lot! Amazing job!

Best regards,

Luis
