### ISSUE TITLE
New Example:How to handle the custom validations in Angular Formly with out adding a Funtion in the JSON data

### ISSUE THREAD

**Issue by kishore016** [formly-js/angular-formly-website#6]
I would like an example that demostrates: How to add the custom validations with out writing a functions in the JSON data.

Currently we have example to add custom validation with writing a functions in JSON data., We want put the validations functions in a seperate JS file and access them.

Please provide an example.

**Comment by kentcdodds** [comment]
[This egghead.io lesson](https://egghead.io/lessons/angularjs-angular-formly-default-options) demonstrates how to create a type that holds the function to do validation. You can also watch [this lesson](https://egghead.io/lessons/angularjs-angular-formly-custom-validation) to learn about custom validators.

Is that sufficient?

**Comment by kentcdodds** [comment]
Note: Depending on the validation needed, you can provide a string as a validator (serializable to JSON). Closing for now. Please let me know if you need more help.
