### ISSUE TITLE
New Example: Classes on individual fields

### ISSUE THREAD

**Issue by holtjonathan** [formly-js/angular-formly-website#60]
I would like an example that demonstrates:  how to recreate a form that I currently use.  Each label/input type is wrapped in a div.  That div has the class 'form__section'.  This class was created by my company so it can handle all of the standard sizing/aligning/formatting/etc.  So I basically have to use this class.

I recently found angular-formly and would love to switch over to it.  However, after doing some research today, nothing is jumping out at me of how to recreate something like this.  Do you have time to help me out?

PS - Formly looks awesome!  I really hope that I can do what I need to do with it so I can convince the powers that be at my work to use it.  Thanks man!

**Comment by kentcdodds** [comment]
This is totally possible. You may not be able to easily use the angular-formly-templates-bootstrap templates. You'd have to create your own. What you'll do is create a `wrapper` ([example](http://angular-formly.com/#/example/advanced/template-wrappers) [docs](http://docs.angular-formly.com/docs/formlyconfig#setwrapper)) that adds the `div` and `label` for your fields.

**Comment by holtjonathan** [comment]
Kent,

Thanks for the response.  I saw those examples that you posted.  Maybe I am just not seeing how you correctly use wrappers or something.  How would I create a wrapper that would add the div class to my fields?

**Comment by kentcdodds** [comment]
[Here you go](https://jsbin.com/jofuve/edit?html,js,output) :-)

**Comment by holtjonathan** [comment]
Awesome!  I'll take a look at this later tonight.  Thanks for the quick support.

**Comment by holtjonathan** [comment]
Kent,

I finally had the chance to look at your example.  Thanks again for the help.  It is definitely a step in the right direction.  But now I have a follow up question :-)

I was hoping that once I saw how you created the wrapper that I would be able to do the rest of this myself but the concept seems to escape me right now.  With the wrapper that you provided, I am able to wrap the label/control in a div with the appropriate class (awesome).  However, now the control within this div needs its own div.  This 'innerdiv' will tell our CDN how to display the control.  For example:

 <div class="form__section">
    <label id="lblSharePercentageIndividual" class="form__label">Share Percentage</label>
    <div class="form__input--xsmall">
        <input name="sharePercentage"</input>
     </div>

The input has the form__input class and this is used to display this input beside the Shared Percentage label before it.  If I run my webpage and manually add these classes (via the chrome debugger) everything lines up the way that I want.  

Do I need to create another wrapper (or something) so that the various controls can have their own div/class?  Keep in mind that not every control has the same class (form__input--xsmall in this example).  Some of them have form__input--small or form__input--date or whatever.

Thanks again for the help!

**Comment by holtjonathan** [comment]
Actually, I think that I just got it.

I created a new formlyConfig type.  I put the class on the input within this type while still referencing the wrappers that you provided.  It seems to work fine.

```
formlyConfig.setType({
    name: 'xsmallInput',
    template: '<input class="form__input--large" ng-model="model[options.key]" />',
    wrapper: ['labelWrapper', 'sectionClass']
});
```

So now, I just create the various types that I need (input--small, input--date, etc) and just use those types when I need to.

Thanks :)
