### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by uncamoe** [formly-js/angular-formly-website#61]
I would like an example that demonstrates: using a link (<a ng-click="launchFunction">text</a>) to launch a function. Currently I am trying to set the ng-click in the formlyConfig.setType template.

It does not work :)
![screenshot-localhost 3000 2015-07-30 15-34-34](https://cloud.githubusercontent.com/assets/725254/8995733/8dd5d114-36d0-11e5-9b2b-14e73d398738.png)

**Comment by kentcdodds** [comment]
Take a look at [this example](http://angular-formly.com/#/example/other/button) which is similar.

**Comment by uncamoe** [comment]
@kentcdodds Thank you for your quick response. I saw this a few days ago when you first put it up. I am trying to get it to work, I just decided to swap the link for one of these buttons, I am however, having an issue with the controller inside the formlyConfig.setType.

**Comment by kentcdodds** [comment]
What problems are you having?
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by uncamoe** [comment]
I was getting errors from the apiCheck functions in there. I do appreciate your help, however i decided to go with a different solution. I am just including a button in between the formly form tags that fires off a function. I just dont have any more time to spend trying to get this to work. I will have other modules coming up that i will want to try this again. So I hope you wont mind if I jump back on this thread at that point in time and ask for more help/clarification. I am in a love/hate relationship with angular at this point. I have been trying to teach it to myself for about 6 months now. I need more experience. :)

**Comment by kentcdodds** [comment]
Sounds good. Once you need help, I recommend following the instructions here: http://help.angular-formly.com good luck!
