### ISSUE TITLE
max length is not working with ng-currecny

### ISSUE THREAD

**Issue by hrishi1183** [formly-js/angular-formly-website#64]
i m trying to use ng-currency to format my currency with a max-length property..
but as ng-currency updates the $viewValue, it goes beyond max-length and fails the validation

You can see the issue below...
http://jsbin.com/gimuwacudo/edit?js,output

can anybody suggest how can we change the run-time maxlength for a field in formly

**Comment by kentcdodds** [comment]
@hrishi1183, thanks for using angular-formly. I don't think that I'll make an example for this one. It's not general enough to be helpful for others. If you need help, please follow the instructions here: http://help.angular-formly.com

**Comment by hrishi1183** [comment]
below is the jsbin example for ng-currency validaiton
http://jsbin.com/kazuyubiqu/1/edit?js,output
