### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by HemavathiJ** [formly-js/angular-formly-website#66]
I would like an example that demonstrates: Advanced Layout(using Panels)

**Comment by kentcdodds** [comment]
Could you be more specific about what you mean by "Panels" ?

**Comment by HemavathiJ** [comment]
Hi, Basically i have tabs having forms in it. Each individual tab contains different layout or structure( i.e., like sections and subsections. In that each section have a heading and some fields which are grouped under that corresponding heading.)

**Comment by kentcdodds** [comment]
Here's a [tabs example](http://angular-formly.com/#/example/integrations/ui-bootstrap-tabs). Here's a [panel example](http://angular-formly.com/#/example/other/nested-formly-forms). Hopefully that's enough to get you going.

**Comment by HemavathiJ** [comment]
Yeah.. that's perfect.. Thank you.. :)
