### ISSUE TITLE
New Example: Table Form

### ISSUE THREAD

**Issue by aabrook** [formly-js/angular-formly-website#7]
I would like an example that demonstrates:
Displaying a completed form in a table format like a log book or excel format. Using templates doesn't seem clear or to work at all

**Comment by kentcdodds** [comment]
Hmmm... I'm not sure I understand what you're describing. Could you give me a wireframe or something?

**Comment by aabrook** [comment]
I've figured out what I need to do. I'll try to come up with an example to share in the next couple of days.
BTW, formly is fantastic!

**Comment by aabrook** [comment]
I've posted a quick example here:
http://dumptext.com/aKHZga2M

What I would like is to configure formly to add a new row to the table and edit that instead of opening a modal with the form. This meets my immediate needs though

**Comment by kentcdodds** [comment]
when I go to that, I get "Blocked"...

-Kent C. Dodds

**Comment by aabrook** [comment]
How about this link: http://pastebin.com/QTLQAwky

**Comment by kentcdodds** [comment]
That's terrific! That helps with #4 as well... I'll create an official example based on this for the website. Thanks!

**Comment by kentcdodds** [comment]
This is now on the website: http://angular-formly.com/#/example/integrations/ui-bootstrap-modal thanks!

**Comment by aabrook** [comment]
Awesome. Glad I could help!
