### ISSUE TITLE
New Example: re-use formly fields

### ISSUE THREAD

**Issue by ghost** [formly-js/angular-formly-website#70]
I would like an example that demonstrates a form to add a model and a form to edit that model that share the same fields without throwing the error:

"Formly Warning: Attempting to overwrite"...

and plus reusing the fields would make the controllers much slimmer...

**Comment by ckniffen** [comment]
One way I do this is if I find there is a field a keep using over an over is I will extend the type and create a new one with defaults that I keep using.

**Comment by ghost** [comment]
hey man! I went ahead and used a service to configure the formly.

**Comment by kentcdodds** [comment]
Going to go ahead and close this one then. Thanks @ckniffen!
