### ISSUE TITLE
New Example: Get values from fields during OnSubmit call

### ISSUE THREAD

**Issue by holtjonathan** [formly-js/angular-formly-website#71]
I would like an example that demonstrates: how to get values from the fields during an OnSubmit call.

I currently have something like this:

```
vm.occupationInfoFields = [
        {
            key: 'occupation',
            type: 'occupationSelect'
        }
    ];
```

``` html
<form ng-submit="vm.onSubmit()" name="vm.occupationInfoForm" novalidate>
    <formly-form model="vm.occupationInfo" fields="vm.occupationInfoFields" form="vm.occupationInfoForm">
        <button type="submit"  class="btn">SUBMIT</button>
    </formly-form>
</form>
```

When the submit button is pressed, the OnSubmit function is being called.  However, when I look at vm.occupationInfoForm, I am not seeing a way to get the selected value of occupation.  I would have thought that vm.occupationInfoForm.occupation (the key of the field) would have contained the value that I needed but it is always undefined.

Am I missing something?  This seems so basic and simple :-(

Thanks,
Holty

**Comment by kentcdodds** [comment]
The values are assigned to the `model` that you pass in. So instead of `vm.occupationInfoForm.occupation`, your values will be on `vm.occupationInfo.occupation`.

I'm going to close this one. If you need help, follow the instructions here: http://help.angular-formly.com
