### ISSUE TITLE
Advanced layout improvements.

### ISSUE THREAD

**Issue by blowsie** [formly-js/angular-formly-website#77]
I was using the CSS code in the advanced layout demo and realised it seemed a bit hacky, and kinda broke my page

Unless I'm missing something;
**This...**

```
body {
  margin: 20px
}

.formly-field {
  margin-bottom: 16px;
}

.formly.row, .formly.row .formly-field {
  margin-bottom: 0;
}

.formly.row .formly-field:first-child {
  padding-left: 0;
}

.formly.row .formly-field:nth-last-child(2) {
  padding-right: 0;
}

.formly-field-group ng-form {
  margin: 0;
}
```

**Can be simplified to this...**

```
body {
  margin: 20px
}

.formly.row{
  display:block;
}
```

**Example**
http://jsbin.com/gufekoxeyi/1/edit?html,css,js,output

**Comment by kentcdodds** [comment]
Awesome! I've updated the example (added a little margin for the **Address** section label). This is great :-) Much simpler!
