### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by neilyoung** [formly-js/angular-formly-website#8]
I would like an example that demonstrates:

... the correct validation of an IP

http://angular-formly.com/#/example/custom-types/default-options

...does not complain about this: 1.1.1.1.1.1.1.1.1.1.1.

**Comment by kentcdodds** [comment]
It's a basic validator. You'll have to find your own regex that validates the way you want to...

**Comment by neilyoung** [comment]
Yes, of course. Found the validator later in the code :) No issue
