### ISSUE TITLE
Add user to angular-formly site: new-user for "Who uses angular-formly?"

### ISSUE THREAD

**Issue by dannycallaghan** [formly-js/angular-formly-website#82]
# Add tillr to users

Project/Company Name: tillr

Link: http://tillr.io

Logo:

![logo for tillr]()

Short Description:

tillr is a London based startup software provider helping public services and small businesses manage their team, tasks and workload simply. Whether you want to monitor the status of a project, increase your productivity or track the overall progress of your business, tillr can help.

Naturally, a business generates a lot of data. According to our customers, one of the most powerful features of tillr is the ability to capture that data, using client facing forms rendered by formly. tillr have also developed an in-house GUI that allows non-developers to build formly forms quickly and easily.

---

**Comment by dannycallaghan** [comment]
![tillr](https://cloud.githubusercontent.com/assets/724781/10512119/ec88803e-7335-11e5-8bf1-ed3f07dc8f17.png)

**Comment by kentcdodds** [comment]
Awesome! I'll get this added later today. Thanks :-)

**Comment by dannycallaghan** [comment]
Hi @kentcdodds . I see this was pushed to master and the issue closed two days ago, but it's still not up there - any idea when we'll be able to see it? It's just that I told my boss it was there, when you made the commit :/

Thanks!

**Comment by kentcdodds** [comment]
I'm terribly sorry about that. I redeployed it, but forgot to build it before I did (so I just redeployed old code). I should probably automate this all with Travis... Need to get around to doing that though. Thanks for your patience. It's up now!

**Comment by dannycallaghan** [comment]
No apology is necessary! Thanks so much, looks great.
