### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by titxoo** [formly-js/angular-formly-website#88]
Color picker example not working 

http://jsbin.com/yogiye/11/edit?js,output

**Comment by kentcdodds** [comment]
cc @benoror

**Comment by kentcdodds** [comment]
I think it's just that the scripts haven't been updated. Please see [new-example.angular-formly.com](http://new-example.angular-formly.com) for the latest of how they should appear.

**Comment by benoror** [comment]
Done! Thanks for reporting @tiagocedrim :smile:

**Comment by titxoo** [comment]
Thanks @benoror :+1:
