### ISSUE TITLE
npmcdn

### ISSUE THREAD

**Issue by sukrosono** [formly-js/angular-formly-website#96]
is npmcdn is down right now?
i cant access example on http://angular-formly.com/ for 3 days, on my place it because fail get formly.js and api-check.js.

**Comment by kentcdodds** [comment]
It's working fine for me.

**Comment by sukrosono** [comment]
@kentcdodds what browser you use dude?
I just realize i had that problem when using chrome
![npmcdn](https://cloud.githubusercontent.com/assets/3001652/12721915/b4d11ce6-c934-11e5-891f-56d4fce7a987.png)

**Comment by kentcdodds** [comment]
Yeah, that's odd. I use Chrome. It works for me in Chrome, Firefox, and Safari.

**Comment by sukrosono** [comment]
@kentcdodds Thank for your response, i think it because karma, but closing it still have same issue. Check Chrome it's up to date, never mind i still can use Firefox
